name: Events
baseurl: "/events/"
highlighter: rouge
exclude:
  - .bundle
  - .git
  - .gitignore
  - bin
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
markdown: kramdown
future: true
collections:
- events
